### ISSUE TITLE
cannot import name 'launch'

### ISSUE THREAD

**Issue by deathemperor** [miyakogi/pyppeteer#10]
Hi,

I'm trying to run the example but got this error:

Traceback (most recent call last):
  File "pyppeteer.py", line 2, in <module>
    from pyppeteer import launch
  File "test\pyppeteer.py", line 2, in <module>
    from pyppeteer import launch
ImportError: cannot import name 'launch'

Tried and failed on both Mac and Windows.

**Comment by Roger535** [comment]
It should be:
'from pyppeteer.launcher import launch'

**Comment by deathemperor** [comment]
I've tried that. it failed too.

**Comment by deathemperor** [comment]
I got this on Windows:

```
D:\xxx\pyppeteer\tests>python test.py
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
[W:pyppeteer.chromium_downloader] chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: C:\Users\xxx\.pyppeteer\local-chromium\497674
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 13, in main
    await browser.close()
  File "C:\Python36\lib\site-packages\pyppeteer\browser.py", line 34, in close
    asyncio.get_event_loop().run_until_complete(self._connection.dispose())
  File "C:\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Python36\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python36\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\xxx\\.pyppeteer\\.dev_profile\\tmpcml6o4ff\\CrashpadMetrics-active.pma'

```

it's confusing that I can run the test.py in pyppeteer\tests (and receive above error)  but if I make another file with the same content anywhere I got this

```
> python pyppeteer.py
Traceback (most recent call last):
  File "pyppeteer.py", line 6, in <module>
    from pyppeteer.launcher import launch
  File "D:\xxx\xxx\test\pyppeteer.py", line 6, in <module>
    from pyppeteer.launcher import launch
ModuleNotFoundError: No module named 'pyppeteer.launcher'; 'pyppeteer' is not a package
```

**Comment by dimitry12** [comment]
The line causing the error is `await browser.close()` - which I don't really need for my use-case (I run Chrome in a separate Docker container).

**Comment by Zulko** [comment]
I got the same error when installing the pypi version (pip install pyppeteer) but it runs ok when installing the github version.

```
sudo python3.6 -m pip install -U git+https://github.com/miyakogi/pyppeteer.git@dev
```

**Comment by miyakogi** [comment]
In the latest version, this issue is fixed.

**Comment by welovemicro** [comment]
You need to change the name of your script from pyppeteer.py as it is "trying to import from itself"

> File "pyppeteer.py", line 2, in
