### ISSUE TITLE
add the isNavigationRequest attribute for request

### ISSUE THREAD

**Issue by tigerfsh** [miyakogi/pyppeteer#107]
Sorry to disturb you @miyakogi  , I add the `isNavigationRequest` attribute for `request`, and I just changed the [network_manager.py](http://39.104.173.226/network_manager.py) file. Unfortunately, all my requests are aborted! Looking forward to your reply.

**Comment by wackazong** [comment]
Could you elaborate on that please? Why do you think I am the person to ask for help here?

**Comment by tigerfsh** [comment]
@wackazong Just a mistake, sorry for that ...

**Comment by miyakogi** [comment]
Just take a look at your file, looks good to me.
How about changing `event['isNavigationRequest']` to `event.get('isNavigationRequest')`

**Comment by tigerfsh** [comment]
I have followed your advice, but the problem still exits!
test coding is as following:
~~~
#! /usr/bin/env python

import asyncio
from pyppeteer import launch


async def request(req):
    if req.isNavigationRequest:
        print("It's a navigation request.")
        await req.abort()


async def main():
    browser = await launch()
    page = await browser.newPage()

    await page.setRequestInterception(True)

    page.on('request', request)

    await page.goto("https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8")

    await page.evaluate("""
    () => {
    nodes = document.all;
    for (let i=0;i<nodes.length;i++){
    nodes[i].click();
    }
    }
    
    """)

    await browser.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
~~~

**Comment by miyakogi** [comment]
Callback function of `page.on` must not be a coroutine function and needs `await req.continue()` if not aborted.
This test case would help you.
https://github.com/miyakogi/pyppeteer/blob/dev/tests/test_network_manager.py#L164

**Comment by tigerfsh** [comment]
### coding:
~~~
#! /usr/bin/env python

import asyncio
from pyppeteer import launch


async def interception(req):
    if req.isNavigationRequest:
        await req.abort()
    else:
        await req.continue_()


async def main():
    browser = await launch(headless=True)
    page = await browser.newPage()

    await page.setRequestInterception(True)

    page.on('request', lambda req: asyncio.ensure_future(interception(req)))

    await page.goto("https://www.python.org/")

    # await page.evaluate("""
    # () => {
    # nodes = document.all;
    # for (let i=0;i<nodes.length;i++){
    # nodes[i].click();
    # }
    # }
    #
    # """)
    print(await page.content())

    await browser.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()

~~~
### result:
~~~
Traceback (most recent call last):
  File "/home/tiger/Documents/DigapisSpider/demo.py", line 39, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/tiger/Documents/DigapisSpider/demo.py", line 22, in main
    await page.goto("https://www.python.org/")
  File "/home/tiger/.local/share/virtualenvs/DigapisSpider-hosG9EyF/lib/python3.6/site-packages/pyppeteer-0.0.19-py3.6.egg/pyppeteer/page.py", line 743, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_FAILED at https://www.python.org/

~~~
@miyakogi It seems like something is wrong with `network_manager.py` file. I'm a little confused ...

**Comment by miyakogi** [comment]
You are also aborting the request to `https://www.python.org/`.
This is correct result.
See https://github.com/miyakogi/pyppeteer/blob/dev/tests/test_page.py#L690

For example, this code may work as you expected:

```python
async def interception(req):
    if req.isNavigationRequest and req.url != "https://www.python.org/":
        await req.abort()
    else:
        await req.continue_()
```

**Comment by tigerfsh** [comment]
### code:
~~~
class Test(object):
    def __init__(self, url):
        self.url = url
        self.loop = asyncio.get_event_loop()

    async def interception(self, req):
        if req.isNavigationRequest and req.url != self.url:
            await req.abort()
        else:
            await req.continue_()

    async def crawl(self):
        browser = await launch()
        page = await browser.newPage()

        await page.setRequestInterception(True)

        page.on('request', lambda req: asyncio.ensure_future(self.interception(req)))

        await page.goto(self.url)
        print("before click, url: ", page.url)

        await page.evaluate("""
        () => {
        nodes = document.all;
        nodes[24].click();
        }
        """)
        await page.waitForNavigation()

        print("after click, url: ", page.url)
        print(await page.content())

    def run(self):
        self.loop.run_until_complete(self.crawl())


if __name__ == '__main__':
    t = Test("http://demo.aisec.cn/demo/aisec/")
    t.run()

~~~
### result: 
~~~
before click, url:  http://demo.aisec.cn/demo/aisec/
after click, url:  chrome-error://chromewebdata/
<html><head></head><body></body></html>

Process finished with exit code 0
~~~
@miyakogi In the code, `nodes[24].click()` will update the url of the current page without interception. 
According to the result of the test, some errors occured in the page. what happened? Any ideas?

**Comment by miyakogi** [comment]
Sorry, I don't have any ideas now.

**Comment by tigerfsh** [comment]
@miyakogi It is long overdue, but I would like to thank you for your help. and this code maybe helpful for others:
~~~
    async def request_interception(**kwargs):
        req = kwargs.get('req')
        page_url = kwargs.get('url')
        if req.url.strip('/') != page_url.strip('/'):
            return await req.abort('aborted')
        else:
            return await req.continue_()
~~~
