### ISSUE TITLE
Node is either not visible or not an HTMLElement - how to click on a link/button?

### ISSUE THREAD

**Issue by sevagh** [miyakogi/pyppeteer#119]
I have some code like:

```python
sign_in_button = await page.waitFor('//html/body/div[2]/div[2]/div[1]/nav/section/ul[2]/li[3]/a[1]')
pprint(vars(sign_in_button))
await page.waitFor(6000)
await sign_in_button.focus()
await sign_in_button.click()
```
I don't really need the `waitFor(6000)` but I stuck it in there just to rule out possible page load errors.

Here's the output of the `pprint`:

```
{'_client': <pyppeteer.connection.CDPSession object at 0x7f0c7c0e2f98>,
 '_context': <pyppeteer.execution_context.ExecutionContext object at 0x7f0c7c102ba8>,
 '_disposed': False,
 '_frameManager': <pyppeteer.frame_manager.FrameManager object at 0x7f0c7c1021d0>,
 '_page': <pyppeteer.page.Page object at 0x7f0c7c0e2fd0>,
 '_remoteObject': {'className': 'HTMLAnchorElement',
                   'description': 'a.Nav-signIn.button.secondary.secondary-background.selected',
                   'objectId': '{"injectedScriptId":2,"id":5}',
                   'subtype': 'node',
                   'type': 'object'}}
```
From the `_remoteObject{'description'}` field (`a.Nav-signIn.button.secondary.secondary-background.selected`), I'm certain that I found the correct element on the page.

However, I can't figure out how to click this? 

```
Traceback (most recent call last):
  File "./autobibliothera.py", line 41, in <module>
    asyncio.get_event_loop().run_until_complete(main(book))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "./autobibliothera.py", line 35, in main
    await sign_in_button.click()
  File "/home/sevagh/.local/lib/python3.6/site-packages/pyppeteer/element_handle.py", line 124, in click
    obj = await self._visibleCenter()
  File "/home/sevagh/.local/lib/python3.6/site-packages/pyppeteer/element_handle.py", line 83, in _visibleCenter
    box = await self._assertBoundingBox()
  File "/home/sevagh/.local/lib/python3.6/site-packages/pyppeteer/element_handle.py", line 96, in _assertBoundingBox
    'Node is either not visible or not an HTMLElement')
pyppeteer.errors.ElementHandleError: Node is either not visible or not an HTMLElement
```

How am I supposed to click on this element?

Thanks.

**Comment by miyakogi** [comment]
This issue may be related to https://github.com/miyakogi/pyppeteer/issues/111 and fixed by the latest release.
