### ISSUE TITLE
Integration with 'pytest-asyncio'

### ISSUE THREAD

**Issue by amit-traiana** [miyakogi/pyppeteer#124]
I am having a strange issues when combining `pyppeeer`, `pytest` and `pytest-asyncio`. Here's the code example:

```
from pyppeteer import launch

import pytest

@pytest.mark.asyncio
async def test_pyppeteer():
    """ Test """
    browser = await launch(headless=False)
    page = await browser.newPage()
    await page.goto('www.bad_url.com')

    await browser.close()
```

Running the above code using `pytest` will make `pytest` freeze. I'm not sure why, but it looks like it happens here:

` await self.connection.send('Browser.close')`

The command is executed successfully, but it's never done waiting for some reason. Everything works just fine if no Exception will be thrown during the test.
Please let me know if you need more debugging information.

**Comment by tigerfsh** [comment]
**My environment:**

* Pyppeteer version: 0.0.19(dev)
* Platform / OS version: Ubuntu 16.0.4
* Python version: 3.6.5

 > Running the above code using pytest will make pytest freeze. 

It doesn't for me. and keep in mind, **no reproduce, no help**.

**Comment by amit-traiana** [comment]
I tested it on two machines so far and was able to reproduce it in both. However, since It didn't reproduce on your machine, I tried it on a third machine, and it indeed working. I'll try to figure the differences between the environments. 

The more I investigate the more it looks like a asyncio issue, and not pyppeteer. Feel free to close this bug until I'll have more details regarding the differences. 

Thanks.

**Comment by amit-traiana** [comment]
More information. I was able to make the following code to run:

```
from pyppeteer import launch
import pytest

@pytest.yield_fixture
def loop():
     loop = asyncio.new_event_loop()
     asyncio.set_event_loop(loop)
     yield loop

def test_some_asyncio_code(loop):
    async def inner():
        browser = await launch()
        page = await browser.newPage()
        raise Exception('Unexpected Exception')
        await browser.close()

    loop.run_until_complete(inner())
```

The difference is that in the example above, the loop is not being closed

**Comment by amit-traiana** [comment]
Closed by mistake.

**Comment by miyakogi** [comment]
It reproduced on my environment, but I couldn't find solution now.

* Pyppeteer version: 0.0.20
* Platform: Arch Linux
* Python version: 3.6.6

**Comment by amit-traiana** [comment]
@miyakogi Thanks for the answer :-)

I was doing some more research:

```
from pyppeteer import launch
import pytest

@pytest.yield_fixture
def loop():
     loop = asyncio.new_event_loop()
     asyncio.set_event_loop(loop)
     yield loop

def test_some_asyncio_code(loop):
    async def inner():
        browser = await launch()
        page = await browser.newPage()
        raise Exception('Unexpected Exception')
        await browser.close()

    loop.run_until_complete(inner())
```

This works. I think it's because I do not close the loop, and let Python handle it once the process is dead. I'm assuming `pytest-asyncio` create an event-loop before each test, and close it. Closing the event_loop makes `pyppeteer` wait forever, as the loop no longer exists. Asyncio is new to me, so I'm not sure if that would be a correct practice, but the fact they both use the same event loop might be an issue? shouldn't `pypeteer` be using it own event loop and therefore avoid colliding `pytest-asyncio` when the event loop is closed by `pytest-asyncio`?

**Comment by miyakogi** [comment]
Thank you for information.
I'm sorry, but I couldn't find good solution to support pytest-asyncio.

**Comment by miyakogi** [comment]
I found the problem.
This is caused by conflict with pytest-asyncio and pyppeteer's auto close function at exit process.
In `dev` branch, `launch` has `autoClose` option.
Please try with this option:

```
pip install -U git+git://github.com/miyakogi/pyppeteer@dev
```

```python
browser = launch(headless=False, autoClose=False)
```

Note that when this option is disabled pyppeteer does not close browser process automatically.

**Comment by amit-traiana** [comment]
Thanks for checking it out again miyakogi. Pytest no longer freeze, but instead crash because the event loop is already closed (when using `autoClost=False`):

```
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 1299, in call_exception_handler
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1336, in error
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1443, in _log
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1453, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 864, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1070, in emit
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1060, in _open
NameError: name 'open' is not defined
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f56a76a0990>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/envs/frontend-acceptance-tests/lib/python3.6/site-packages/pyppeteer/connection.py", line 60, in _recv_loop
  File "/home/amitz/.pyenv/versions/3.6.6/envs/frontend-acceptance-tests/lib/python3.6/site-packages/websockets/py35/client.py", line 6, in __aexit__
  File "/home/amitz/.pyenv/versions/3.6.6/envs/frontend-acceptance-tests/lib/python3.6/site-packages/websockets/protocol.py", line 393, in close
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/tasks.py", line 342, in wait_for
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 544, in call_later
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 554, in call_at
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 1299, in call_exception_handler
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1336, in error
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1443, in _log
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1453, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 864, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1070, in emit
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1060, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 1299, in call_exception_handler
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1336, in error
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1443, in _log
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1453, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 864, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1070, in emit
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1060, in _open
NameError: name 'open' is not defined
Exception ignored in: <generator object WebSocketCommonProtocol.close_connection at 0x7f56a76a0ca8>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/envs/frontend-acceptance-tests/lib/python3.6/site-packages/websockets/protocol.py", line 853, in close_connection
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/streams.py", line 312, in close
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/selector_events.py", line 621, in close
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 575, in call_soon
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 1299, in call_exception_handler
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1336, in error
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1443, in _log
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1453, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 864, in handle
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1070, in emit
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py", line 1060, in _open
NameError: name 'open' is not defined
Exception ignored in: <generator object Queue.get at 0x7f56a76c4830>
Traceback (most recent call last):
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/queues.py", line 169, in get
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 575, in call_soon
  File "/home/amitz/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by miyakogi** [comment]
This code raise error but runs all tests (result includes test_pyppeteer2):

```python
from pyppeteer import launch
import pytest

@pytest.mark.asyncio
async def test_pyppeteer():
    """ Test """
    browser = await launch(
        headless=False,
        autoClose=False,
        args=['--no-sandbox'],  # need for my environment
    )
    page = await browser.newPage()
    await page.goto('http://www.bad_url.com')
    await browser.close()

def test_pyppeteer2():
    assert True
```

Results:

```
$ pytest -v issue124.py

=============================== test session starts ================================
platform linux -- Python 3.6.6, pytest-3.7.1, py-1.5.4, pluggy-0.7.1 -- /home/takagi/.virtualenvs/arch/pyppeteer/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/takagi/Projects/pyppeteer, inifile:
plugins: xdist-1.22.5, forked-0.2, asyncio-0.9.0
collected 2 items                                                                  

issue124.py::test_pyppeteer FAILED                                           [ 50%]
issue124.py::test_pyppeteer2 PASSED                                          [100%]

===================================== FAILURES =====================================
__________________________________ test_pyppeteer __________________________________

    @pytest.mark.asyncio
    async def test_pyppeteer():
        """ Test """
        browser = await launch(
            headless=False,
            autoClose=False,
            args=['--no-sandbox'],  # need for my environment
        )
        page = await browser.newPage()
>       await page.goto('http://www.bad_url.com')

issue124.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyppeteer.page.Page object at 0x7f091dfb9940>
url = 'http://www.bad_url.com', options = {}, kwargs = {}, referrer = ''
set_request = <function Page.goto.<locals>.set_request at 0x7f091dfdad08>
eventListeners = [{'emitter': <pyppeteer.network_manager.NetworkManager object at 0x7f091dfb9e48>, 'eventName': 'request', 'handler': <function Page.goto.<locals>.set_request at 0x7f091dfdad08>}]
mainFrame = <pyppeteer.frame_manager.Frame object at 0x7f091dfb9da0>
timeout = 30000
watcher = <pyppeteer.navigator_watcher.NavigatorWatcher object at 0x7f091dfb9c18>
result = 'net::ERR_NAME_NOT_RESOLVED at http://www.bad_url.com'

    async def goto(self, url: str, options: dict = None, **kwargs: Any
                   ) -> Optional[Response]:
        """Go to the ``url``.
    
            :arg string url: URL to navigate page to. The url should include
                scheme, e.g. ``https://``.
    
            Available options are:
    
            * ``timeout`` (int): Maximum navigation time in milliseconds, defaults
              to 30 seconds, pass ``0`` to desable timeout. The default value can
              be changed by using the :meth:`setDefaultNavigationTimeout` method.
            * ``waitUntil`` (str|List[str]): When to consider navigation succeeded,
              defaults to ``load``. Given a list of event strings, navigation is
              considered to be successful after all events have been fired. Events
              can be either:
    
              * ``load``: when ``load`` event is fired.
              * ``documentloaded``: when the ``DOMContentLoaded`` event is fired.
              * ``networkidle0``: when there are no more than 0 network connections
                for at least 500 ms.
              * ``networkidle2``: when there are no more than 2 network connections
                for at least 500 ms.
            """
        options = merge_dict(options, kwargs)
        referrer = self._networkManager.extraHTTPHeaders().get('referer', '')
        requests: Dict[str, Request] = dict()
    
        def set_request(request: Request) -> None:
            if request.url not in requests:
                requests[request.url] = request
    
        eventListeners = [helper.addEventListener(
            self._networkManager, NetworkManager.Events.Request,
            set_request,
        )]
    
        mainFrame = self._frameManager.mainFrame
        if mainFrame is None:
            raise PageError('No main frame.')
        timeout = options.get('timeout', self._defaultNavigationTimeout)
        watcher = NavigatorWatcher(self._frameManager, mainFrame, timeout,
                                   options)
    
        result = await self._navigate(url, referrer)
        if result is not None:
>           raise PageError(result)
E           pyppeteer.errors.PageError: net::ERR_NAME_NOT_RESOLVED at http://www.bad_url.com

pyppeteer/page.py:746: PageError
======================== 1 failed, 1 passed in 0.74 seconds ========================
Task was destroyed but it is pending!
task: <Task pending coro=<Connection._recv_loop() running at /home/takagi/Projects/pyppeteer/pyppeteer/connection.py:57> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f091de80af8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/protocol.py:528> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f091dfe0048>()]> cb=[<TaskWakeupMethWrapper object at 0x7f091de80a08>(), _wait.<locals>._on_completion() at /usr/lib64/python3.6/asyncio/tasks.py:380]>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() running at /home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/protocol.py:805> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() running at /home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/protocol.py:528> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f091dfe0048>()]> cb=[<TaskWakeupMethWrapper object at 0x7f091de80a08>(), _wait.<locals>._on_completion() at /usr/lib64/python3.6/asyncio/tasks.py:380]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at /usr/lib64/python3.6/asyncio/queues.py:155> cb=[_wait.<locals>._on_completion() at /usr/lib64/python3.6/asyncio/tasks.py:380]>
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f091e77beb8>
Traceback (most recent call last):
  File "/home/takagi/Projects/pyppeteer/pyppeteer/connection.py", line 63, in _recv_loop
    await asyncio.sleep(0)
  File "/home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/py35/client.py", line 6, in __aexit__
    await self.ws_client.close()
  File "/home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/protocol.py", line 393, in close
    self.timeout, loop=self.loop)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 342, in wait_for
    timeout_handle = loop.call_later(timeout, _release_waiter, waiter)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 544, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 554, in call_at
    self._check_closed()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <generator object WebSocketCommonProtocol.close_connection at 0x7f091dfe83b8>
Traceback (most recent call last):
  File "/home/takagi/.virtualenvs/arch/pyppeteer/lib/python3.6/site-packages/websockets/protocol.py", line 853, in close_connection
    self.writer.close()
  File "/usr/lib64/python3.6/asyncio/streams.py", line 312, in close
    return self._transport.close()
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 621, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 575, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<NavigatorWatcher._createTimeoutPromise.<locals>._timeout_func() running at /home/takagi/Projects/pyppeteer/pyppeteer/navigator_watcher.py:85> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f091de80168>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<wait() running at /usr/lib64/python3.6/asyncio/tasks.py:313> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f091de80d38>()]> cb=[NavigatorWatcher.__init__.<locals>.<lambda>() at /home/takagi/Projects/pyppeteer/pyppeteer/navigator_watcher.py:53]>
```

**Comment by amit-traiana** [comment]
Yes, it's the same here. It runs the tests, but when the process exits, I'm getting the same error as you do (`raise RuntimeERror('event loop is closed')).

**Comment by miyakogi** [comment]
I have experimentally implemented `loop` option to `launch` function.
Although got the same result, this is better option for your purpose.
Usage:

```python
from pyppeteer import launch
import pytest

@pytest.mark.asyncio
async def test_pyppeteer(event_loop):
    """ Test """
    browser = await launch(
        headless=False,
        loop=event_loop,
        args=['--no-sandbox'],  # need for my environment
    )
    page = await browser.newPage()
    await page.goto('http://www.bad_url.com')
    await browser.close()
```

**Comment by amit-traiana** [comment]
Is the event loop I can pass now will be the one your using?

**Comment by nikan1996** [comment]
```
import pytest
from pyppeteer import launch
from pyppeteer.errors import NetworkError


@pytest.mark.asyncio
async def test_pyppeteer():
    """ Test """
    browser = await launch(headless=False)
    page = await browser.newPage()
    try:
        await page.goto('www.bad_url.com')
    except NetworkError:
        page.close()
    await browser.close()
```
I think the Error should be catched otherwise the browser will not close while error raised

**Comment by nikan1996** [comment]
Now the example is ok in pyppeteer 0.0.21,
but hang in pyppeteer 0.0.20.
My environment:
pytest: 3.7.3
python: 3.6.6
OS: ubuntu 14.04
@miyakogi
