### ISSUE TITLE
page.type('2222222') raise error

### ISSUE THREAD

**Issue by Roger535** [miyakogi/pyppeteer#13]
hi,

`await page.click('input[name="password"]')
await page.type('2222222')`

when I select a input element and type something，it raise error：
`Task exception was never retrieved
future: <Task finished coro=<Page.press() done, defined at /usr/local/lib/python3.6/site-packages/pyppeteer/page.py:688> exception=KeyError('2',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/page.py", line 696, in press
    await self._keyboard.up(key)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/input.py", line 61, in up
    self._pressedKeys.remove(key)
KeyError: '2'`

while I change the code like this：
`      await page.type('2')
        await page.type('2')
        await page.type('2')
        await page.type('2')
        await page.type('2')`        

it work

**Comment by d33tah** [comment]
@Roger535 Hi! Do you still have the problem? Could you provide more details?

**Comment by MadTinker** [comment]
This is fixed with the timeout patch correct?
