### ISSUE TITLE
Chromium is not installing for windows 7 when i executed the command: pyppeteer-install for the latest version of pyppeteer0.0.21

### ISSUE THREAD

**Issue by Shivumtr95** [miyakogi/pyppeteer#132]
C:\Users\shivaraj.hp>pyppeteer-install 
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
0it [00:00, ?it/s][W:pyppeteer.chromium_downloader]
chromium download done.
514it [00:00, 513914.72it/s]
Traceback (most recent call last):
  File "C:\Users\shivaraj.hp\AppData\Local\Programs\Python\Python36\Scripts\pyppeteer-install-script.py", line 11, in <module>
    load_entry_point('pyppeteer==0.0.21', 'console_scripts', 'pyppeteer-install')()
  File "c:\users\shivaraj.hp\appdata\local\programs\python\python36\lib\site-packages\pyppeteer\command.py", line 14, in install 
  download_chromium()
  File "c:\users\shivaraj.hp\appdata\local\programs\python\python36\lib\site-packages\pyppeteer\chromium_downloader.py", line 127, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "c:\users\shivaraj.hp\appdata\local\programs\python\python36\lib\site-packages\pyppeteer\chromium_downloader.py", line 115, in extract_zip
    with ZipFile(data) as zf: File "c:\users\shivaraj.hp\appdata\local\programs\python\python36\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "c:\users\shivaraj.hp\appdata\local\programs\python\python36\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file

**Comment by miyakogi** [comment]
Looks failing to download chromium.
Please check you can access to https://storage.googleapis.com/chromium-browser-snapshots/ and can download chromium manually from https://storage.googleapis.com/chromium-browser-snapshots/Win/575458/chrome-win32.zip
