### ISSUE TITLE
Chromium download script is possibly open for writing when trying to execute

### ISSUE THREAD

**Issue by stellarhoof** [miyakogi/pyppeteer#145]
I'm getting errors after downloading chromium:

```
Traceback (most recent call last):
  ......
    browser = await launch(args=['--no-sandbox'])
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 169, in launch
    **options,
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 26] Text file busy: '/root/.local/share/pyppeteer/local-chromium/575458/chrome-linux/chrome'
```

This is a wild guess but could it be that when chromium is downloading, that specific file is still open for writing? See https://stackoverflow.com/questions/26625166/subprocess-breaking-pipes-and-file-busy

**Comment by stellarhoof** [comment]
I need to investigate more. I will get back to you. Thanks for the prompt reply.

**Comment by stellarhoof** [comment]
We run our scripts in parallel so this might be part of a race condition issue. (See https://github.com/miyakogi/pyppeteer/issues/152). For now I will leave open and close once I don't see this error for a reasonable amount of time (perhaps 1 week).
