### ISSUE TITLE
downloading chromium in the first run fails if it's called from concurrent.futures.ThreadPoolExecutor

### ISSUE THREAD

**Issue by sinancetinkaya** [miyakogi/pyppeteer#147]
```
Traceback (most recent call last):
  File "D:\test\scrap.py", line 500, in get
    content = self.reader(session, url)
  File "D:\test\scrap.py", line 526, in reader
    response.html.render()
  File "D:\Program Files\Python\Python36-32\lib\site-packages\requests_html.py", line 572, in render
    self.session.browser  # Automatycally create a event loop and browser
  File "D:\Program Files\Python\Python36-32\lib\site-packages\requests_html.py", line 679, in browser
    self.loop = asyncio.get_event_loop()
  File "D:\Program Files\Python\Python36-32\lib\asyncio\events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "D:\Program Files\Python\Python36-32\lib\asyncio\events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
```

**Comment by miyakogi** [comment]
In the traceback message, there is nothing from pyppeteer's.
It seems to be a problem of requests-html.
