### ISSUE TITLE
Connection unexpectedly closed yield another exception of asyncio.base_futures.InvalidStateError

### ISSUE THREAD

**Issue by cnicodeme** [miyakogi/pyppeteer#149]
Hi!

I've stumbled upon this issue by accident and tried to find a solution on my own but couldn't.
Working on my code, I made a coding mistake which resulted in having Chrome close the connection abnormaly. What follows this is what is interesting for Pyppeteer I believe ; The next call hangs and the code never respond until a kill signal.

Here's a sample code showing my issue, with comments where necessary:

```python
import asyncio
from pyppeteer import launch
from pyppeteer.navigator_watcher import NavigatorWatcher
from pyppeteer.network_manager import NetworkManager
from pyppeteer import helper

async def browse(page, source):
    # The timeouts here are low because the result is the same with longer one, and we don't have 48h in a day
    navigate_options = {'waitUntil': ['load', 'documentloaded', 'networkidle0'], 'timeout': 1500}

    navigation_requests = {}
    def set_request(req):
        print("Got requests !")
        print(req._requestId)

        # The following will fail because "requests" does not exists, it should be "navigation_requests"
        # This is not the bug I'm looking to fix (duh ;)) but this error at this point is causing a later, more important issue
        if req.url not in requests:
            navigation_requests[req._requestId] = req

    # I'm doing the following because setContent works for raw HTML
    # But Chrome doesn't wait for ressources loaded from this, to be completed (external CSS/JS)
    # By implementing this code, I was hoping it would work.
    eventListeners = [helper.addEventListener(
        page._networkManager,
        NetworkManager.Events.Request,
        set_request,
    )]

    watcher = NavigatorWatcher(page._frameManager, page.mainFrame, navigate_options.get('timeout'), navigate_options)
    await page.setContent(source)
    result = await watcher.navigationPromise()
    watcher.cancel()
    helper.removeEventListeners(eventListeners)

    # Again, this would fails. We need to use "navigation_requests", not "requests"
    request = requests.get(page.mainFrame._navigationURL)
    return await page.screenshot({'path': '/tmp/example.png'})

async def main(source):
    browser = await launch()
    context = await browser.createIncogniteBrowserContext()
    page = await context.newPage()

    task = asyncio.ensure_future(browse(page, source))
    try:
        # TODO: #NOPASS
        await asyncio.wait_for(task, timeout=2)
        return task.result()
    except Exception as e:
        # We go there because the timeout from asyncio.wait_for is reached

        if not task.cancelled():
            task.cancel()

        try:
            await task
        except Exception as sub:
            # We have the correct error here!
            # This works great
            raise sub

        raise e
    finally:
        # This is where the REAL ISSUE arise
        # Since our previous code had an issue, Chrome closed the connection abnormaly
        # So when we will call setJavaScriptEnabled, it won't work

        # But I didn't find a way to catch the inside exception
        # (I'll post the stack trace later)
        await page.setJavaScriptEnabled(False)
        # THE BIG ISSUE is that the previous line hangs indefinitely that way, and the program is stuck...
        await page.goto('about:blank')
        await page.close()
        await context.close()


try:
    asyncio.get_event_loop()
except RuntimeError:
    asyncio.set_event_loop(asyncio.new_event_loop())

asyncio.get_event_loop().run_until_complete(main('<html><body><img src="https://avatars0.githubusercontent.com/u/317142?s=40&v=4" alt="hello" />Hello World</body></html>'))
```

The main issue is located at `await page.setJavaScriptEnabled(False)`. Since the connection has been closed previously, calling `await page.setJavaScriptEnabled(False)` will fail, but I haven't find a way to tell Pyppeteer to handle that exception.

So in that current state, the code hangs there forever.

Here's the stack trace displayed when the error occurs:

> [E:pyppeteer.connection] connection unexpectedly closed
> Task exception was never retrieved
> future: <Task finished coro=<Connection._async_send() done, defined at /home/cnicodem/www/project//env/lib/python3.6/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state',)>
> Traceback (most recent call last):
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/pyppeteer/connection.py", line 73, in _async_send
>     await self.connection.send(msg)
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/websockets/protocol.py", line 334, in send
>     yield from self.ensure_open()
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/websockets/protocol.py", line 470, in ensure_open
>     raise ConnectionClosed(self.close_code, self.close_reason)
> websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/pyppeteer/connection.py", line 79, in _async_send
>     await self.dispose()
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/pyppeteer/connection.py", line 170, in dispose
>     await self._on_close()
>   File "/home/cnicodem/www/project//env/lib/python3.6/site-packages/pyppeteer/connection.py", line 153, in _on_close
>     f'Protocol error {cb.method}: Target closed.',  # type: ignore
> asyncio.base_futures.InvalidStateError: invalid state

I tried to work on the pyppeteer/connection.py file to catch the exception, but wasn't able to succeed. I must say that I'm not an expert in Asyncio too ;)

**Comment by cnicodeme** [comment]
For now, the workaround that I have found, that works, but still displays the InvalidStateError, is the following:

In the `finally` block:

```python
try:
    await asyncio.wait_for(page.setJavaScriptEnabled(False), timeout=0.25)
except Exception as e:
    pass

try:
    await page.goto('about:blank')
except Exception as e:
    pass

try:
    await page.close()
    await context.close()
except Exception as e:
    pass
```

In this case, the page.goto will fail with a KeyError (when looking for the specific callback on the connection.py class)

And the page.close / context.close will fail with ConnectionError.

Hope that helps, I'm curious to know how this will be handled.

**Comment by NishantTharani** [comment]
@cnicodeme 

Hi. Thanks for opening this, it gave me some insight into what is going on with my own code. I'm having a similar issue, but not in the same domain, and I was wondering if you could help me out. 

Basically, you seem to understand what is leading Chrome to close the connection abnormally in your code - but I don't. I too have a coroutine that I await with a timeout, and that timeout is reached, and then my following code fails. Does reaching the timeout in an async.wait_for() block automatically lead to Chrome closing the connection to pyppeteer abnormally? Is there no way to have a wait_for block that simply carries on without closing the connection if the timeout is reached?

**Comment by cnicodeme** [comment]
Hi @CannedSurprise ,

> Does reaching the timeout in an async.wait_for() block automatically lead to Chrome closing the connection to pyppeteer abnormally?

I'd say no. Your code part should kill the connection, not Chrome... but maybe Chrome as a timeout system in place to kill connections after a certain time?

> Is there no way to have a wait_for block that simply carries on without closing the connection if the timeout is reached?

I don't think the timeout will close the connection here (if you are referring to the task's timeout, not Chrome's). For the second part of your question, I think it's the issue I'm having so we have to wait from the devs here to share some insights ;)

**Comment by NishantTharani** [comment]
Hi @cnicodeme 

Thanks for the response :)

I've tried using the timeout functionality built directly into the Chrome DevTools API to do the same thing I was trying to do with pyppeteer and there was no error/connection being killed. So it appears to be something that's not inherent to Chrome.

Anyway, I will wait for insights with you, thanks again :)

**Comment by cnicodeme** [comment]
@CannedSurprise That's interesting! So by using the timeout from Chrome DevTools, you didn't had the issue anymore? If I understand correctly, that's something we can dig !

**Comment by NishantTharani** [comment]
@cnicodeme Yes! The issue arises with a chrome page that has a dialog box open which is blocking the API connection to it. When I do something like DOM.getDocument(_timeout=5) from the Chrome DevTools API it works no problem. But when I do something like:


try:
  page = await asyncio.wait_for(target.page(), timeout=3.0)  
  return page  
except asyncio.TimeoutError:  
  print("Warning: asyncio TimeoutError occurred")  


The connection appears to get closed abnormally

(I tried inserting this as code but all the line breaks vanished :s )

**Comment by cnicodeme** [comment]
I have this one liner to ignore dialogs, maybe that would help?

```python
page.on('dialog', lambda dialog: dialog.dismiss())
```

**Comment by NishantTharani** [comment]
Thanks for the tip. I tried it but it doesn't work. Strange because the dialog is definitely a javascript Dialog of the 'alert' type that is supposed to be handled by this listener. The dialog looks exactly like this one in fact:

https://i.stack.imgur.com/TrPdu.png

Except without the 'prevent this page from creating additional dialogs' checkbox at the bottom. 

In fact, even when I try to test the listener with some generated dialogs at http://www.htmlbasix.com/alert.shtml it doesn't seem to work. Can you think of any reason it might not be working?

**Comment by cnicodeme** [comment]
Maybe I have a solution for you. When you run Chrome, did you add the "--disable-popup-blocking" parameter? This one might help you ;)

**Comment by NishantTharani** [comment]
I do not. I tried to add it but did not notice a difference. What should adding the flag do? Would it prevent the pop-up altogether in theory or would it enable your one-liner (page.on...) to work?

**Comment by cnicodeme** [comment]
It should disable popup blocking ;) From my understanding, it would enable the one liner to work.

**Comment by cnicodeme** [comment]
Any news about this issue? I'm still having the error throwed.

**Comment by icedrunkard** [comment]
> @cnicodeme Yes! The issue arises with a chrome page that has a dialog box open which is blocking the API connection to it. When I do something like DOM.getDocument(_timeout=5) from the Chrome DevTools API it works no problem. But when I do something like:
> 
> try:
> page = await asyncio.wait_for(target.page(), timeout=3.0)
> return page
> except asyncio.TimeoutError:
> print("Warning: asyncio TimeoutError occurred")
> 
> The connection appears to get closed abnormally
> 
> (I tried inserting this as code but all the line breaks vanished :s )

any solutions?

**Comment by byt3bl33d3r** [comment]
Just ran into this. @cnicodeme I tried what you suggested. Started Chrome with `--disable-popup-blocking` and used the one-liner and still getting the error.

Any updates?

**Comment by byt3bl33d3r** [comment]
Just FYI for anyone still having this issue. This is what worked for me.

Install Pyppeteer from the dev branch:
`python3 -m pip install -U git+https://github.com/miyakogi/pyppeteer.git@dev`
plus apply the fix detailed here https://github.com/miyakogi/pyppeteer/pull/160#issuecomment-448886155
seems to have solved the above error at least.

**Comment by cnicodeme** [comment]
Unfortunately no, I stopped listening to requests.

**Comment by Mattwmaster58** [comment]
duplicate of #62
