### ISSUE TITLE
ConnectionError:Connection is closed, this is showing when the I run my script on Ubuntu 16.04 ec2 instance, when i run it locally it runs fine! 

### ISSUE THREAD

**Issue by ibrdemolli** [miyakogi/pyppeteer#169]
page = await self.session.browser.newPage()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyppeteer/browser.py", line 192, in newPage
    return await self._defaultContext.newPage()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyppeteer/browser.py", line 329, in newPage
    return await self._browser._createPageInContext(self._id)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyppeteer/browser.py", line 200, in _createPageInContext
    'Target.createTarget', options)).get('targetId')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyppeteer/connection.py", line 85, in send
    raise ConnectionError('Connection is closed')
ConnectionError: Connection is closed

**Comment by ibrdemolli** [comment]
Im using pyppeteer Version: 0.0.25

**Comment by vbxx3** [comment]
~~You need to open browser before page~~
Didn't check the title

**Comment by ibrdemolli** [comment]
im actually opening the browser and it is opening fine!

    def browser(self):
        if not hasattr(self, "_browser"):
            self.loop = asyncio.get_event_loop()
            try:
                self._browser = self.loop.run_until_complete(pyppeteer.launch(headless=True, args=['--no-sandbox']))
                print("Succesfully passed")
            except Exception as ex:
                print(ex)

        return self._browser

**Comment by ibrdemolli** [comment]
here is the code i'm using to recreate it:

import asyncio
from pyppeteer import launch
from bs4 import BeautifulSoup

async def main():
    url = "example.net"
    browser = await launch()
    page = await browser.newPage()
    try:
        await asyncio.sleep(3)
        await page.goto(url, options={'timeout': int(10 * 1000)})
        content = await page.content()
        soup = BeautifulSoup(content, 'lxml')
        bucketArray = soup.find("div", {"id": "quote_latest_from_cnbc_bucket"})
        links = bucketArray.find_all('a')
        print(links[1]['href'])
        await page.close()
        await browser.close()
    except TimeoutError:
        await page.close()
        await browser.close()
        return None


asyncio.get_event_loop().run_until_complete(main())



here is what I get on my server(ec2 instance):

Traceback (most recent call last):
  File "news_crawler/pyppeteer_cnbc.py", line 25, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "news_crawler/pyppeteer_cnbc.py", line 11, in main
    await page.goto(url, options={'timeout': int(10 * 1000)})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyppeteer/page.py", line 862, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 10000 ms exceeded.

**Comment by amarynets** [comment]
Have the same issue in Docker container, but locally all works fine

**Comment by hayd** [comment]
Could be due to https://github.com/miyakogi/pyppeteer/issues/158
