### ISSUE TITLE
libXss.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aaronvigo** [miyakogi/pyppeteer#231]
Hello I'am trying to run a script in heroku but constantly getting that error. I already test some diferents stacks but I still give the error.

`[W:pyppeteer.chromium_downloader]
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /app/.local/share/pyppeteer/local-chromium/575458
Task exception was never retrieved
future: <Task finished coro=<message_sender() done, defined at discord-bot.py:36> exception=BrowserError('Browser closed unexpectedly:\n/app/.local/share/pyppeteer/local-chromium/575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory\n',)>
Traceback (most recent call last):
  File "discord-bot.py", line 39, in message_sender
    await blizz_request()
  File "discord-bot.py", line 22, in blizz_request
    await r.html.arender()
  File "/app/.heroku/python/lib/python3.6/site-packages/requests_html.py", line 615, in arender
    self.browser = await self.session.browser
  File "/app/.heroku/python/lib/python3.6/site-packages/requests_html.py", line 714, in browser
    self._browser = await pyppeteer.launch(ignoreHTTPSErrors=not(self.verify), headless=True, args=self.__browser_args)
  File "/app/.heroku/python/lib/python3.6/site-packages/pyppeteer/launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyppeteer/launcher.py", line 189, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyppeteer/launcher.py", line 233, in _get_ws_endpoint
    self.proc.stdout.read().decode()
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
/app/.local/share/pyppeteer/local-chromium/575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

^CTraceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 589, in run
    loop.run_forever()
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/app/.heroku/python/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/app/.heroku/python/lib/python3.6/site-packages/pyppeteer/launcher.py", line 174, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discord-bot.py", line 50, in <module>
    client.run(TOKEN)
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 595, in run
    _cleanup_loop(loop)
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop, return_exceptions=True))
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 482, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/pyppeteer/launcher.py", line 174, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self._check_closed()
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited`

**Comment by aaronvigo** [comment]
Pyppeteer wasn't installed. Close.
