### ISSUE TITLE
pyppeteer.errors.NetworkError: Protocol error Target.createTarget: Target closed.

### ISSUE THREAD

**Issue by NineSH** [miyakogi/pyppeteer#234]
Traceback (most recent call last):
  File "crawl.py", line 166, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/home/shihui/anaconda3/lib/python3.7/asyncio/base_events.py", line 568, in run_uil_complete
    return future.result()
  File "crawl.py", line 48, in extract_paper
    page = await init_page(browser)
  File "crawl.py", line 31, in init_page
    page = await browser.newPage()
  File "/home/shihui/anaconda3/lib/python3.7/site-packages/pyppeteer/browser.py", line 1, in newPage
    return await self._defaultContext.newPage()
  File "/home/shihui/anaconda3/lib/python3.7/site-packages/pyppeteer/browser.py", line 3, in newPage
    return await self._browser._createPageInContext(self._id)
  File "/home/shihui/anaconda3/lib/python3.7/site-packages/pyppeteer/browser.py", line 2, in _createPageInContext
    'Target.createTarget', options)).get('targetId')
pyppeteer.errors.NetworkError: Protocol error Target.createTarget: Target closed.

This error is escalated when multiple tasks are performed asynchronously，When there's only one URL in it, it's okay to scrapy.

**Comment by ping2balaji** [comment]
I am facing the same issue when i access 3 links one after other and always happens with the 3rd link irrespective of what url it is.
Any help?

**Comment by ping2balaji** [comment]
Issue got fixed after closing the session object with session.close() properly after every usage to crawl or read a page.  (note: session is "session = requests_html.HTMLSession()")

**Comment by NineSH** [comment]
> Issue got fixed after closing the session object with session.close() properly after every usage to crawl or read a page. (note: session is "session = requests_html.HTMLSession()")

Thank you for sharing the methods.

**Comment by lazidoca** [comment]
This issue has been posted many times, to fix it, please downgrade the websockets to version 6.0

pip install websockets==6

**Comment by Mattwmaster58** [comment]
duplicate of #62
