### ISSUE TITLE
I have a crawler and need to log in to multiple accounts at the same time. How does pyppeteer work? I use multiple processes to start multiple chromius. When the second one starts, I get an error: the error is as follows

### ISSUE THREAD

**Issue by 807lwt** [miyakogi/pyppeteer#245]
Traceback (most recent call last):
  File "F:/anliang项目/Boos/test/pyptest.py", line 428, in <module>
    loop.run_until_complete(main(username, pwd, url))
  File "D:\Program Files (x86)\Anaconda\envs\demo4\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "F:/anliang项目/Boos/test/pyptest.py", line 31, in main
    {'headless': False, 'userDataDir': r'F:\anliang', 'dumpio': True})
  File "D:\Program Files (x86)\Anaconda\envs\demo4\lib\site-packages\pyppeteer\launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "D:\Program Files (x86)\Anaconda\envs\demo4\lib\site-packages\pyppeteer\launcher.py", line 189, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "D:\Program Files (x86)\Anaconda\envs\demo4\lib\site-packages\pyppeteer\launcher.py", line 233, in _get_ws_endpoint
    self.proc.stdout.read().decode()
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by 807lwt** [comment]
help！
