### ISSUE TITLE
target closed when a dialog ( for example a geetest captcha) shows

### ISSUE THREAD

**Issue by icedrunkard** [miyakogi/pyppeteer#252]
websockets  == 6.0
[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished coro=<Connection._async_send() done, defined at C:\Python37\lib\site-packages\pyppeteer\connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Python37\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Python37\lib\asyncio\streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyppeteer\connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 361, in send
    yield from self.ensure_open()
  File "C:\Python37\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyppeteer\connection.py", line 79, in _async_send
    await self.dispose()
  File "C:\Python37\lib\site-packages\pyppeteer\connection.py", line 170, in dispose
    await self._on_close()
  File "C:\Python37\lib\site-packages\pyppeteer\connection.py", line 153, in _on_close
    f'Protocol error {cb.method}: Target closed.',  # type: ignore
asyncio.base_futures.InvalidStateError: invalid state

**Comment by icedrunkard** [comment]
https://github.com/icedrunkard/zhilian_login_pyppeteer/blob/d98f5879c18c2c2b4936e7dd7f2233faecb9a3e6/tools/cracker.py#L189
