### ISSUE TITLE
Error browser closes unexpectedly

### ISSUE THREAD

**Issue by MacKey-255** [miyakogi/pyppeteer#287]
Hi, I have a big problem using pyppeteer along with celery. The browser closes unexpectedly, here I leave the error:
ERROR:
```
[2019-12-29 20:01:03,562: WARNING/ForkPoolWorker-3] Traceback (most recent call last):
[2019-12-29 20:01:03,562: WARNING/ForkPoolWorker-3] File "/var/www/publiconmigo/system/libs/nav.py", line 52, in start
    self.browser = await self.get_new_browser()
[2019-12-29 20:01:03,562: WARNING/ForkPoolWorker-3] File "/var/www/publiconmigo/system/libs/nav.py", line 154, in get_new_browser
    browser = await self.launcher.launch()
[2019-12-29 20:01:03,562: WARNING/ForkPoolWorker-3] File "/var/www/python/lib/python3.7/site-packages/pyppeteer/launcher.py", line 189, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
[2019-12-29 20:01:03,562: WARNING/ForkPoolWorker-3] File "/var/www/python/lib/python3.7/site-packages/pyppeteer/launcher.py", line 233, in _get_ws_endpoint
    self.proc.stdout.read().decode()
[2019-12-29 20:01:03,563: WARNING/ForkPoolWorker-3] pyppeteer.errors.BrowserError: Browser closed unexpectedly:
[1229/200102.866499:ERROR:platform_thread_posix.cc(124)] pthread_create: Resource temporarily unavailable (11)
[1229/200102.868321:ERROR:platform_thread_posix.cc(124)] pthread_create: Resource temporarily unavailable (11)
[1229/200102.868368:FATAL:task_scheduler_impl.cc(108)] Check failed: service_thread_->StartWithOptions(service_thread_options). 
#0 0x564bd9a9d79c base::debug::StackTrace::StackTrace()
#1 0x564bd9a1d1c0 logging::LogMessage::~LogMessage()
#2 0x564bd9a61abd base::internal::TaskSchedulerImpl::Start()
#3 0x564bd85dab18 content::BrowserMainLoop::CreateThreads()
#4 0x564bd8946417 content::StartupTaskRunner::RunAllTasksNow()
#5 0x564bd85da83d content::BrowserMainLoop::CreateStartupTasks()
#6 0x564bd85de8e3 content::BrowserMainRunnerImpl::Initialize()
#7 0x564bddb0aec9 headless::HeadlessContentMainDelegate::RunProcess()
#8 0x564bd970fafe content::ContentMainRunnerImpl::Run()
#9 0x564bd9743c0b service_manager::Main()
#10 0x564bd970dbe1 content::ContentMain()
#11 0x564bddb09d8d headless::(anonymous namespace)::RunContentMain()
#12 0x564bddb09e18 headless::HeadlessBrowserMain()
#13 0x564bd974121a headless::HeadlessShellMain()
#14 0x564bd7bc01ac ChromeMain
#15 0x7f5d112e809b __libc_start_main
#16 0x564bd7bc002a _start

Received signal 6
#0 0x564bd9a9d79c base::debug::StackTrace::StackTrace()
#1 0x564bd9a9d301 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f5d13752730 <unknown>
#3 0x7f5d112fb7bb gsignal
#4 0x7f5d112e6535 abort
#5 0x564bd9a9c155 base::debug::BreakDebugger()
#6 0x564bd9a1d629 logging::LogMessage::~LogMessage()
#7 0x564bd9a61abd base::internal::TaskSchedulerImpl::Start()
#8 0x564bd85dab18 content::BrowserMainLoop::CreateThreads()
#9 0x564bd8946417 content::StartupTaskRunner::RunAllTasksNow()
#10 0x564bd85da83d content::BrowserMainLoop::CreateStartupTasks()
#11 0x564bd85de8e3 content::BrowserMainRunnerImpl::Initialize()
#12 0x564bddb0aec9 headless::HeadlessContentMainDelegate::RunProcess()
#13 0x564bd970fafe content::ContentMainRunnerImpl::Run()
#14 0x564bd9743c0b service_manager::Main()
#15 0x564bd970dbe1 content::ContentMain()
#16 0x564bddb09d8d headless::(anonymous namespace)::RunContentMain()
#17 0x564bddb09e18 headless::HeadlessBrowserMain()
#18 0x564bd974121a headless::HeadlessShellMain()
#19 0x564bd7bc01ac ChromeMain
#20 0x7f5d112e809b __libc_start_main
#21 0x564bd7bc002a _start
  r8: 0000000000000000  r9: 00007ffccd4a7dd0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffccd4a8548 r13: 0000000000000080 r14: 00007ffccd4a8550 r15: 00007ffccd4a8558
  di: 0000000000000002  si: 00007ffccd4a7dd0  bp: 00007ffccd4a8020  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f5d112fb7bb  sp: 00007ffccd4a7dd0
  ip: 00007f5d112fb7bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by Mattwmaster58** [comment]
Hi @MacKey-255, it looks like this project has been abandoned. You may want to consider the active fork [pyppeteer2](https://github.com/pyppeteer/pyppeteer2). Feel free to create an issue there if your problem persists with the updated libary.
