### ISSUE TITLE
pyppeteer.errors.BrowserError: Unexpectedly chrome process closed with return code: 127

### ISSUE THREAD

**Issue by ashkov** [miyakogi/pyppeteer#31]
When I run first Readme example script (Example: open web page and take a screenshot), I've got this error:

`python3 example.py
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "example.py", line 5, in main
    browser = launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 161, in launch
    return Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 127, in launch
    raise BrowserError('Unexpectedly chrome process closed with '
pyppeteer.errors.BrowserError: Unexpectedly chrome process closed with return code: 127
`

**Comment by miyakogi** [comment]
Please check chromium can start correctly.

```
cd ~/.pyppeteer/[revision]/chrome-[arch]
./chrome
```

If failed to start chromium, [troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) of puppeteer may help.

**Comment by thomaszdxsn** [comment]
happen for me too

**Comment by ichux** [comment]
On my Mac, to run Chromium, I did

./Users/username/.pyppeteer/local-chromium/533271/chrome-mac/Chromium.app/Contents/MacOS/Chromium

**Comment by Wowgreat** [comment]
I get this error when
`browser = await launch(options={'devtools': True})`
Any one help me, thanks a lot
