### ISSUE TITLE
local variable 'watchdog' referenced before assignment

### ISSUE THREAD

**Issue by cheng10** [miyakogi/pyppeteer#33]
branch dev, When timeout set to 0, commit 158bfaf causes line 98 `if not watchdog.done():`, `UnboundLocalError: local variable 'watchdog' referenced before assignment`

```
Traceback (most recent call last):
  File "./test_pype.py", line 48, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./test_pype.py", line 44, in main
    await page.goto(url, timeout=0)
  File "/home/centos/p3venv/lib64/python3.6/site-packages/pyppeteer/page.py", line 487, in goto
    error = await navigationPromise
  File "/home/centos/p3venv/lib64/python3.6/site-packages/pyppeteer/navigator_watcher.py", line 98, in waitForNavigation
    if not watchdog.done():
UnboundLocalError: local variable 'watchdog' referenced before assignment
```

**Comment by miyakogi** [comment]
Fixed.
Thank you for reporting.
