### ISSUE TITLE
Navigation Timeout Exceeded: 3000 ms exceeded

### ISSUE THREAD

**Issue by thomaszdxsn** [miyakogi/pyppeteer#34]
```shell
Exception in callback NavigatorWatcher.waitForNavigation.<locals>.watchdog_cb(<Task finishe...> result=None>) at /usr/local/lib/python3.6/dist-packages/pyppeteer/navigator_watcher.py:49
handle: <Handle NavigatorWatcher.waitForNavigation.<locals>.watchdog_cb(<Task finishe...> result=None>) at /usr/local/lib/python3.6/dist-packages/pyppeteer/navigator_watcher.py:49>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/navigator_watcher.py", line 52, in watchdog_cb
    self._timeout)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/navigator_watcher.py", line 40, in _raise_error
    raise error
concurrent.futures._base.TimeoutError: Navigation Timeout Exceeded: 3000 ms exceeded
```

Hi, What this mean? is this page can't render?

**Comment by cheng10** [comment]
DO NOT install pyppeteer using `pip install -U git+https://github.com/miyakogi/pyppeteer.git@dev`, the dev branch lacks of tests and is full of bugs right now. Use `pip install pyppeteer`, still full of bugs, but it works in some way.

**Comment by thomaszdxsn** [comment]
actually i used the `requests_html`, it's dependency should not dev version. 

maybe i should reading more source.

**Comment by Dongxuxiang1994** [comment]
Have you solved the problem yet? i have the same problem.

**Comment by Legutier** [comment]
same problem here, used `headless : True` to see the navigator. It seems that even if the navigator loads, pyppeteer still believes is loading

**Comment by abhijain02** [comment]
Hi,

I am facing the same problem here. Any updates on this ? Please let me know if any.
