### ISSUE TITLE
Usaage example has error

### ISSUE THREAD

**Issue by LryBackinblack** [miyakogi/pyppeteer#4]
import asyncio
from pyppeteer.launcher import launch

async def main():
    browser = launch()
    page = await browser.newPage()
    await page.goto('http://example.com')
    await page.screenshot({'path': 'example.png'})
    browser.close()

asyncio.get_event_loop().run_until_complete(main())

run this example and then

Traceback (most recent call last):
  File "D:/Project/Pytho_Project/ComputerVision/pyppe2.py", line 12, in <module>
    loop.run_until_complete(main())
  File "D:\python3.6\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "D:/Project/Pytho_Project/ComputerVision/pyppe2.py", line 9, in main
    browser.close()
  File "D:\python3.6\lib\site-packages\pyppeteer\browser.py", line 34, in close
    asyncio.get_event_loop().run_until_complete(self._connection.dispose())
  File "D:\python3.6\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "D:\python3.6\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

delete browser.close(),can fix it

**Comment by miyakogi** [comment]
Thank you trying pyppeteer and reporting issue!
Fixed by https://github.com/miyakogi/pyppeteer/commit/1930274eea2683c09084d7a22aaea81dad85fa78

Fixed example is:

```python
import asyncio
from pyppeteer.launcher import launch

async def main():
    page = await browser.newPage()
    await page.goto('http://example.com')
    await page.screenshot({'path': 'example.png'})

browser = launch()
asyncio.get_event_loop().run_until_complete(main())
browser.close()
```

**Comment by matanox** [comment]
The above code yields the same error message, with version 0.0.25 (the one coming with pip install at the time of writing).
