### ISSUE TITLE
Support QtWebengine

### ISSUE THREAD

**Issue by zinootje** [miyakogi/pyppeteer#55]
I would like to use pyppeteer to control a QtWebengine. But it throws a error.
```
/usr/bin/python3.6 /home/matty/PycharmProjects/GhostAuto/AutoWeb.py
Traceback (most recent call last):
  File "/home/matty/PycharmProjects/GhostAuto/AutoWeb.py", line 17, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/matty/PycharmProjects/GhostAuto/AutoWeb.py", line 7, in main
    browserWSEndpoint="ws://127.0.0.1:55551/devtools/browser/<id>")
  File "/usr/lib/python3.6/site-packages/pyppeteer/launcher.py", line 263, in connect
    connection, options, None, lambda: connection.send('Browser.close'))
  File "/usr/lib/python3.6/site-packages/pyppeteer/browser.py", line 80, in create
    await connection.send('Target.setDiscoverTargets', {'discover': True})
pyppeteer.errors.NetworkError: Protocol Error: {'code': -32601, 'message': "'Target.setDiscoverTargets' wasn't found"}

```
I think this is because pyppeteer cant get the browser id because "http://127.0.0.1:55551/json/version " doesn't supply it. Maybe it is possible to connect strait to a page

**Comment by miyakogi** [comment]
Pyppeteer won't support other than bundled chromium, sorry.

**Comment by zinootje** [comment]
Okay , I understand. Is it all possible to connect to a page directly
