### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by zhanghaofei** [miyakogi/pyppeteer#56]
pyppeteer==0.0.16

code：
```
# coding:utf-8
import asyncio
from pyppeteer import launch

async def main():
    brower = await launch()
    await brower.close()

asyncio.get_event_loop().run_until_complete(main())
```

error：
```
Error in data transfer
Traceback (most recent call last):
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "D:\code\py3\.venv\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "F:\python3\Lib\asyncio\streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "F:\python3\Lib\asyncio\streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 669, in write_frame
    yield from self.writer.drain()
  File "F:\python3\Lib\asyncio\streams.py", line 329, in drain
    raise exc
  File "F:\python3\Lib\asyncio\selector_events.py", line 761, in write
    n = self._sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "D:\code\py3\.venv\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "F:\python3\Lib\asyncio\streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "F:\python3\Lib\asyncio\streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 669, in write_frame
    yield from self.writer.drain()
  File "F:\python3\Lib\asyncio\streams.py", line 329, in drain
    raise exc
  File "F:\python3\Lib\asyncio\selector_events.py", line 761, in write
    n = self._sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/code/py3/pyppeteer/hello.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "F:\python3\Lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "D:/code/py3/pyppeteer/hello.py", line 11, in main
    await brower.close()
  File "D:\code\py3\.venv\lib\site-packages\pyppeteer\browser.py", line 156, in close
    await self.disconnect()
  File "D:\code\py3\.venv\lib\site-packages\pyppeteer\browser.py", line 160, in disconnect
    await self._connection.dispose()
  File "D:\code\py3\.venv\lib\site-packages\pyppeteer\connection.py", line 139, in dispose
    await self._on_close()
  File "D:\code\py3\.venv\lib\site-packages\pyppeteer\connection.py", line 128, in _on_close
    await self.connection.close()
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 370, in close
    self.timeout, loop=self.loop)
  File "F:\python3\Lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "D:\code\py3\.venv\lib\site-packages\websockets\protocol.py", line 674, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason

Process finished with exit code 1
```

**Comment by tonggang** [comment]
got the same issue

**Comment by miyakogi** [comment]
Thank you for reporting issue with minimal code.

I don't have local windows environment, so it takes time to fix windows specific problems.
Maybe in most situations this problem would be fix in `feat/better_termination` branch.
Could you try this branch?

```
pip install git+https://github.com/miyakogi/pyppeteer/@feat/better_termination
```

**Comment by shiquanwang** [comment]
Get the same error on Mac, Python-3.6.4, pyppeteer-0.0.16
```
Error in data transfer
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/site-packages/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/site-packages/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/site-packages/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/site-packages/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/site-packages/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "/usr/local/miniconda3/envs/pyppeteer_py36/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by zhanghaofei** [comment]
@miyakogi **feat/better_termination** branch does not have this problem,What's the cause?

**Comment by miyakogi** [comment]
Thank you for checking!
Now merged to `dev` branch.
