### ISSUE TITLE
Demo can not run on Windows 7 

### ISSUE THREAD

**Issue by IvanaH** [miyakogi/pyppeteer#59]
Get error when run Example: open web page and take a screenshot:

Error in data transfer
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "D:\Python36\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "D:\Python36\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "D:\Python36\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 669, in write_frame
    yield from self.writer.drain()
  File "D:\Python36\lib\asyncio\streams.py", line 323, in drain
    raise exc
  File "D:\Python36\lib\asyncio\selector_events.py", line 762, in write
    n = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host. 
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "D:\Python36\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "D:\Python36\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "D:\Python36\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 669, in write_frame
    yield from self.writer.drain()
  File "D:\Python36\lib\asyncio\streams.py", line 323, in drain
    raise exc
  File "D:\Python36\lib\asyncio\selector_events.py", line 762, in write
    n = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\JavaL\WorkSpace\PyTest\Test\pyppeteerDemo.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "D:\JavaL\WorkSpace\PyTest\Test\pyppeteerDemo.py", line 9, in main
    await browser.close()
  File "D:\Python36\lib\site-packages\pyppeteer\browser.py", line 156, in close
    await self.disconnect()
  File "D:\Python36\lib\site-packages\pyppeteer\browser.py", line 160, in disconnect
    await self._connection.dispose()
  File "D:\Python36\lib\site-packages\pyppeteer\connection.py", line 139, in dispose
    await self._on_close()
  File "D:\Python36\lib\site-packages\pyppeteer\connection.py", line 128, in _on_close
    await self.connection.close()
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 370, in close
    self.timeout, loop=self.loop)
  File "D:\Python36\lib\asyncio\tasks.py", line 352, in wait_for
    return fut.result()
  File "D:\Python36\lib\site-packages\websockets\protocol.py", line 674, in write_frame
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
![qq 20180402095915](https://user-images.githubusercontent.com/9857603/38180129-b52046bc-365c-11e8-8d4c-0d977109fadd.png)

**Comment by IvanaH** [comment]
I have tried it on win 10 again, and get the same error.

**Comment by tonggang** [comment]
for me it is working on win10

**Comment by miyakogi** [comment]
Duplicated to https://github.com/miyakogi/pyppeteer/issues/56.
Please try `dev` branch.

**Comment by miyakogi** [comment]
New version of pyppeteer has been released.
Please update pyppeteer to 0.0.17.
