### ISSUE TITLE
KeyError: 'webSocketDebuggerUrl'

### ISSUE THREAD

**Issue by teratorn** [miyakogi/pyppeteer#73]
This is code that is/was working on a previous OS (alpine linux), but I'm now deploying in "production" (a fresh alpine 3.7 linux system) and running in to this error... not sure what to expect since this is "working" code...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/home/teratorn/code/catwiz/catwiz/pdf.py", line 58, in _main
    browser = await launch(executablePath=self.exe_path)
  File "/home/teratorn/code/catwiz/venv3/lib/python3.6/site-packages/pyppeteer/launcher.py", line 243, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/teratorn/code/catwiz/venv3/lib/python3.6/site-packages/pyppeteer/launcher.py", line 160, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/home/teratorn/code/catwiz/venv3/lib/python3.6/site-packages/pyppeteer/launcher.py", line 179, in _get_ws_endpoint
    return data['webSocketDebuggerUrl']
KeyError: 'webSocketDebuggerUrl'
```

**Comment by xiaochonzi** [comment]
@teratorn  this is because alpine 3.7 only support chromium version 61. and pyppeteer need chromium  version  above 65 .  and how to reslove your problem , try to rewrite Launch class  change ws_endpoint url , the key webSocketDebuggerUrl in version 61 only appear in /json/list and not in /json/version.
