### ISSUE TITLE
Chromium downloaded automatically but not found (Docker, alpine 3.6//3.7)

### ISSUE THREAD

**Issue by imWildCat** [miyakogi/pyppeteer#79]
pyppeteer: `0.0.17`

Dockerfile (https://github.com/imWildCat/scylla/blob/289c4626eaa4e00604d95d429d2f08b7487706d1/Dockerfile):

```Dockerfile

FROM python:3.6-alpine3.7 as build

RUN apk add --update --no-cache g++ gcc libxslt-dev make build-base curl-dev openssl-dev

RUN mkdir -p /var/www/scylla
WORKDIR /var/www/scylla

RUN pip install scylla

FROM python:3.6-alpine3.7

LABEL maintainer="WildCat <wildcat.name@gmail.com>"

RUN apk add --update --no-cache libxslt-dev curl-dev openssl-dev

COPY --from=build /usr/local/lib/python3.6/site-packages/ /usr/local/lib/python3.6/site-packages/

WORKDIR /var/www/scylla
VOLUME /var/www/scylla

EXPOSE 8899
EXPOSE 8081

CMD python -m scylla

```

Error logs:

```bash
[W:pyppeteer.chromium_downloader] chromium extracted to: /root/.pyppeteer/local-chromium/543305
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/scylla/scheduler.py", line 34, in fetch_ips
    html = worker.get_html(url, render_js=provider.should_render_js())
  File "/usr/local/lib/python3.6/site-packages/scylla/worker.py", line 47, in get_html
    response.html.render(wait=1.5, timeout=10.0)
  File "/usr/local/lib/python3.6/site-packages/requests_html.py", line 572, in render
    self.session.browser  # Automatycally create a event loop and browser
  File "/usr/local/lib/python3.6/site-packages/requests_html.py", line 680, in browser
    self._browser = self.loop.run_until_complete(pyppeteer.launch(headless=True, args=['--no-sandbox']))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 243, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 141, in launch
    env=env,
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.pyppeteer/local-chromium/543305/chrome-linux/chrome': '/root/.pyppeteer/local-chromium/543305/chrome-linux/chrome'
```

Actually, the file is there:

```bash
~/.pyppeteer/local-chromium/543305/chrome-linux # ls -lh
total 239556
drwxr-xr-x    2 root     root        4.0K May 31 15:49 MEIPreload
-rwxr-xr-x    1 root     root      189.3M May 31 15:49 chrome
-rw-r--r--    1 root     root        5.0K May 31 15:49 chrome-wrapper
-rw-r--r--    1 root     root      802.2K May 31 15:49 chrome_100_percent.pak
-rw-r--r--    1 root     root        1.0M May 31 15:49 chrome_200_percent.pak
-rw-r--r--    1 root     root       22.7K May 31 15:49 chrome_sandbox
-rw-r--r--    1 root     root        9.7M May 31 15:49 icudtl.dat
-rw-r--r--    1 root     root      359.0K May 31 15:49 libEGL.so
-rw-r--r--    1 root     root        6.1M May 31 15:49 libGLESv2.so
-rw-r--r--    1 root     root        2.6M May 31 15:49 libclearkeycdm.so
drwxr-xr-x    2 root     root        4.0K May 31 15:49 locales
-rw-r--r--    1 root     root        3.2M May 31 15:49 nacl_helper
-rw-r--r--    1 root     root        9.5K May 31 15:49 nacl_helper_bootstrap
-rw-r--r--    1 root     root        3.5M May 31 15:49 nacl_helper_nonsfi
-rw-r--r--    1 root     root        3.5M May 31 15:49 nacl_irt_x86_64.nexe
-rw-r--r--    1 root     root      171.0K May 31 15:49 natives_blob.bin
-rw-r--r--    1 root     root        2.5K May 31 15:49 product_logo_48.png
drwxr-xr-x    3 root     root        4.0K May 31 15:49 resources
-rw-r--r--    1 root     root       12.0M May 31 15:49 resources.pak
drwxr-xr-x    2 root     root        4.0K May 31 15:49 swiftshader
-rw-r--r--    1 root     root        1.7M May 31 15:49 v8_context_snapshot.bin
-rw-r--r--    1 root     root       36.5K May 31 15:49 xdg-mime
-rw-r--r--    1 root     root       32.5K May 31 15:49 xdg-settings
~/.pyppeteer/local-chromium/543305/chrome-linux #
```

**Comment by imWildCat** [comment]
Closed due to lack of response.

**I'll eliminate this library from my code**

**Comment by bcatubig** [comment]
Can you reopen this? I am experiencing this issue as well. Hoping someone else might be able to provide some insight

**Comment by bcatubig** [comment]
@imWildCat I was able to get this working by modifying my Dockerfile and launcher options

```
RUN apk -U add chromium udev ttf-freefont
```

and 

```python
pyppeteer.launch(
            headless=True,
            executablePath="/usr/bin/chromium-browser",
            args=['--no-sandbox', '--disable-gpu']
        )
```

**Comment by sandys** [comment]
@bcatubig 	can you please post your working dockerfile to get  pyppeteer  working in an alpine Docker image ? im trying to build this, but am unsuccessful

**Comment by dave7280** [comment]
Same problem...

**Comment by Elessar8** [comment]
Same here...

**Comment by pythme** [comment]
me too
