### ISSUE TITLE
UnicodeDecodeError: 'ascii'...

### ISSUE THREAD

**Issue by juansgaitan** [miyakogi/pyppeteer#96]
Python = 3.5.3

I'm trying to `easy-install` & `pip3 install` `pyppeteer` inside a docker env.
```
Processing pyppeteer-0.0.19.tar.gz
Writing /tmp/easy_install-bvsos692/pyppeteer-0.0.19/setup.cfg
Running pyppeteer-0.0.19/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bvsos692/pyppeteer-0.0.19/egg-dist-tmp-ncnbevep
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-bvsos692/pyppeteer-0.0.19/setup.py", line 27, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py_backwards/compiler.py", line 85, in compile_files
    dependencies.update(_compile_file(paths, target))
  File "/usr/local/lib/python3.5/dist-packages/py_backwards/compiler.py", line 57, in _compile_file
    code = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2317: ordinal not in range(128)
```

**Comment by miyakogi** [comment]
First of all, pyppeteer's python3.5 support is experimental.

The error seems to be caused by encoding.
Please check `$LANG` environmental variable supports unicode, like `en_US.UTF-8`.

**Comment by juansgaitan** [comment]
`$LANG` is set to `en_US.UTF-8`

**Comment by miyakogi** [comment]
hmm...
So, it seems [py-backwards](https://github.com/nvbn/py-backwards)'s issue.

Error raised from simple `read()` function, which uses system's encoding setting.
Please check [locale.getpreferredencoding](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) returns correct encoding.

**Comment by miyakogi** [comment]
I have updated not to include non-ascii characters (maybe).
Please try github's dev branch.
