### ISSUE TITLE
Why latest Chrome don't allow redirection by default ?

### ISSUE THREAD

**Issue by makelove** [miyakogi/pyppeteer#98]
https://storage.googleapis.com/chromium-browser-snapshots/Mac/571375/chrome-mac.zip

pyppeteer.__version__
'0.0.19'

What happen ?
Why ?
I don't like this !

**Comment by miyakogi** [comment]
I couldn't understand the problem.
I tested osx high sierra, it seems to work correctly with redirect.
Please let me know more details.

**Comment by makelove** [comment]
I found out it is because I am using 
```
def print_request_url(request):
    print('请求：',request.url)
page.on('request',f=print_request_url)
```
then Chrome will not allow redirection
![2018-07-10 16 13 39](https://user-images.githubusercontent.com/6279340/42497681-aefbce02-845c-11e8-9599-a1acaa76fc91.png)

what should I do ?

request.continue()

**Comment by miyakogi** [comment]
Sorry, I can't read Chinese...

Does it also occur when manually accessing the page by the bundled chromium?
If so, it would be a new feature of the chrome/chromium.
Currently I don't have any idea to prevent this behavior, sorry.

**Comment by Germey** [comment]
He means that pyppeteer prevents redirects by default.

I also meet this issue.

For example my blog:
[http://cuiqingcai.com](http://cuiqingcai.com)  --- auto redirect --> [https://cuiqingcai.com(https://cuiqingcai.com)  

http will be redirected to https.

But I've test it with pyppeteer with this code:

```python
import asyncio
import pyppeteer


def render(url, retries=8, script=None, wait=0.2, scrolldown=False, sleep=0,
           timeout=8.0, keep_page=False, browser=None, with_result=False):
    """
    render page with pyppeteer
    :param url: page url
    :param retries: max retry times
    :param script: js script to evaluate
    :param wait: number of seconds to wait before loading the page, preventing timeouts
    :param scrolldown: how many times to page down
    :param sleep: how many long to sleep after initial render
    :param timeout: the longest wait time, otherwise raise timeout error
    :param keep_page: keep page not to be closed, browser object needed
    :param browser: pyppetter browser object
    :param with_result: return with js evaluation result
    :return: content, [result]
    """
    # get event loop
    loop = asyncio.get_event_loop()
    
    # init browser
    if not browser:
        browser = loop.run_until_complete(pyppeteer.launch(headless=True, args=['--no-sandbox']))
    
    # define async render
    async def async_render(url, script, scrolldown, sleep, wait, timeout, keep_page):
        try:
            # basic render
            page = await browser.newPage()
            await asyncio.sleep(wait)
            await page.goto(url, options={'timeout': int(timeout * 1000)})
            
            result = None
            # evaluate with script
            if script:
                result = await page.evaluate(script)
            
            # scroll down for {scrolldown} times
            if scrolldown:
                for _ in range(scrolldown):
                    await page._keyboard.down('PageDown')
                    await asyncio.sleep(sleep)
            else:
                await asyncio.sleep(sleep)
            if scrolldown:
                await page._keyboard.up('PageDown')
            
            # get html of page
            content = await page.content()
            
            # if keep page, do not close it
            if not keep_page:
                await page.close()
            return content, result
        except TimeoutError:
            return None
    
    content, result = None, None
    # retry for {retries} times
    for i in range(retries):
        if not content:
            content, result = loop.run_until_complete(
                async_render(url=url, script=script, sleep=sleep, wait=wait,
                             scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
        else:
            break
    
    # if need to return js evaluation result
    if with_result:
        return content, result
    return content


if __name__ == '__main__':
    url = 'http://cuiqingcai.com'
    result = render(url, timeout=30)
    print(result)
    with open('page.html', 'w', encoding='utf-8') as f:
        f.write(result)
```

It gets:

```
Traceback (most recent call last):
  File "/private/var/py/RequestsHTML/render.py", line 79, in <module>
    result = render(url, timeout=8)
  File "/private/var/py/RequestsHTML/render.py", line 67, in render
    scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/private/var/py/RequestsHTML/render.py", line 34, in async_render
    await page.goto(url, options={'timeout': int(timeout * 1000)})
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/page.py", line 659, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 8000 ms exceeded.
```

But If I change the scheme to `https`, it works fine. 

So I think pyppeteer prevents redirect by default.

I think it's better to set allow redirect to True.

**Comment by Germey** [comment]
My environment:
patform: osx 10.13.3
python: 3.6.1  
pyppeteer: 0.0.19

**Comment by Germey** [comment]
Oh my god. If I change `headless=False`, redirects are allowed.
But it doesn't work while I setting `headless=True`....
